Better detection of the resolver library

diff --git a/SRC/plugins/dns/configure b/SRC/plugins/dns/configure
--- a/SRC/plugins/dns/configure
+++ b/SRC/plugins/dns/configure
@@ -18986,13 +18986,9 @@ fi
 done
 
 if test "$DNS_BUILD" != "0"; then
-
-for ac_func in res_init
-do
-as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for $ac_func" >&5
-echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
-if eval "test \"\${$as_ac_var+set}\" = set"; then
+ echo "$as_me:$LINENO: checking for res_mkquery" >&5
+echo $ECHO_N "checking for res_mkquery... $ECHO_C" >&6
+if test "${ac_cv_func_res_mkquery+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
@@ -19001,12 +18997,12 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-/* Define $ac_func to an innocuous variant, in case <limits.h> declares $ac_func.
+/* Define res_mkquery to an innocuous variant, in case <limits.h> declares res_mkquery.
    For example, HP-UX 11i <limits.h> declares gettimeofday.  */
-#define $ac_func innocuous_$ac_func
+#define res_mkquery innocuous_res_mkquery
 
 /* System header to define __stub macros and hopefully few prototypes,
-    which can conflict with char $ac_func (); below.
+    which can conflict with char res_mkquery (); below.
     Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
     <limits.h> exists even on freestanding compilers.  */
 
@@ -19016,7 +19012,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 # include <assert.h>
 #endif
 
-#undef $ac_func
+#undef res_mkquery
 
 /* Override any gcc2 internal prototype to avoid an error.  */
 #ifdef __cplusplus
@@ -19025,14 +19021,14 @@ extern "C"
 #endif
 /* We use char because int might match the return type of a gcc2
    builtin and then its argument prototype would still apply.  */
-char $ac_func ();
+char res_mkquery ();
 /* The GNU C library defines this for functions which it implements
     to always fail with ENOSYS.  Some functions are actually named
     something starting with __ and the normal name is an alias.  */
-#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
+#if defined (__stub_res_mkquery) || defined (__stub___res_mkquery)
 choke me
 #else
-char (*f) () = $ac_func;
+char (*f) () = res_mkquery;
 #endif
 #ifdef __cplusplus
 }
@@ -19041,7 +19037,7 @@ char (*f) () = $ac_func;
 int
 main ()
 {
-return f != $ac_func;
+return f != res_mkquery;
   ;
   return 0;
 }
@@ -19067,38 +19063,47 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  eval "$as_ac_var=yes"
+  ac_cv_func_res_mkquery=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-eval "$as_ac_var=no"
+ac_cv_func_res_mkquery=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
-if test `eval echo '${'$as_ac_var'}'` = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
-_ACEOF
-
+echo "$as_me:$LINENO: result: $ac_cv_func_res_mkquery" >&5
+echo "${ECHO_T}$ac_cv_func_res_mkquery" >&6
+if test $ac_cv_func_res_mkquery = yes; then
+  :
 else
-  	echo "$as_me:$LINENO: checking $ac_func again by including <resolv.h>" >&5
-echo $ECHO_N "checking $ac_func again by including <resolv.h>... $ECHO_C" >&6
-	 LIBS=-lresolv cat >conftest.$ac_ext <<_ACEOF
+
+echo "$as_me:$LINENO: checking for res_mkquery in -lbind" >&5
+echo $ECHO_N "checking for res_mkquery in -lbind... $ECHO_C" >&6
+if test "${ac_cv_lib_bind_res_mkquery+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lbind  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <resolv.h>
 
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char res_mkquery ();
 int
 main ()
 {
-$ac_func();
+res_mkquery ();
   ;
   return 0;
 }
@@ -19124,20 +19129,107 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
+  ac_cv_lib_bind_res_mkquery=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-{ echo "$as_me:$LINENO: WARNING: No DNS resolver development environment found, not building this plugin" >&5
-echo "$as_me: WARNING: No DNS resolver development environment found, not building this plugin" >&2;} && DNS_BUILD=0
-
+ac_cv_lib_bind_res_mkquery=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
 fi
-done
+echo "$as_me:$LINENO: result: $ac_cv_lib_bind_res_mkquery" >&5
+echo "${ECHO_T}$ac_cv_lib_bind_res_mkquery" >&6
+if test $ac_cv_lib_bind_res_mkquery = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBBIND 1
+_ACEOF
+
+  LIBS="-lbind $LIBS"
+
+else
+
+echo "$as_me:$LINENO: checking for res_mkquery in -lresolv" >&5
+echo $ECHO_N "checking for res_mkquery in -lresolv... $ECHO_C" >&6
+if test "${ac_cv_lib_resolv_res_mkquery+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lresolv  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char res_mkquery ();
+int
+main ()
+{
+res_mkquery ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_resolv_res_mkquery=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_resolv_res_mkquery=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_resolv_res_mkquery" >&5
+echo "${ECHO_T}$ac_cv_lib_resolv_res_mkquery" >&6
+if test $ac_cv_lib_resolv_res_mkquery = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBRESOLV 1
+_ACEOF
+
+  LIBS="-lresolv $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: No DNS resolver development environment found, not building this plugin" >&5
+echo "$as_me: error: No DNS resolver development environment found, not building this plugin" >&2;}
+   { (exit 1); exit 1; }; } && DNS_BUILD=0
+fi
+
+fi
+
+fi
 
 fi
 
